# Generated by Django 2.2.7 on 2019-11-20 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0003_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='company',
            new_name='contact',
        ),
    ]
