# Generated by Django 2.2.7 on 2019-11-26 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0004_auto_20191120_1847'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('user_name', models.CharField(max_length=50)),
                ('contact', models.IntegerField()),
                ('password', models.CharField(max_length=50)),
                ('Confirm_password', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
