# Generated by Django 2.2.7 on 2019-11-26 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0005_auto_20191126_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='contact',
            field=models.CharField(max_length=10),
        ),
    ]
