# Generated by Django 2.2.7 on 2019-11-26 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0006_auto_20191126_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='Confirm_password',
        ),
    ]
